### ISSUE TITLE
On opening "Other-Other" Menu I get an 404

### ISSUE THREAD

**Issue by Hobbabobba** [PREngineer/nZEDb-deploy#4]
when i try to open `http://myip/browse?t=0000` it show´s me a `404`.

Besides that, everything is working fine.

**Comment by PREngineer** [comment]
I have seen that too but that is beyond the scope of the installation as it is an nZEDb issue per se.

**Comment by PREngineer** [comment]
Technically you should be able to disable the link to the last OTHER in the menu in the 

Admin Functions > Edit Categories

Go to the very end and DISABLE the Other with ID '1000001'.

However, there is something wrong with nZEDb and the developers need to fix this because the disablement doesn't work for that category.

Hope that helps you understand what is going on.
![screen shot 2017-02-09 at 1 02 10 am](https://cloud.githubusercontent.com/assets/6334069/22771257/a6a7d416-ee63-11e6-9499-8b19806dd7cd.png)
